name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  IMAGE_NAME: greenbluegreen/bg-stremio-addon

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: tags
        run: |
          TAG="${GITHUB_REF_NAME}"
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "sha7=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build and push (linux/amd64)
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${IMAGE_NAME}:${{ steps.tags.outputs.tag }} \
            -t ${IMAGE_NAME}:${{ steps.tags.outputs.tag }}-${{ steps.tags.outputs.sha7 }} \
            -t ${IMAGE_NAME}:latest \
            --push .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tags.outputs.tag }}
          name: ${{ steps.tags.outputs.tag }}
          draft: false
          prerelease: false
          body: |
            Image tags pushed:
            - `${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.tag }}`
            - `${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.tag }}-${{ steps.tags.outputs.sha7 }}`
            - `${{ env.IMAGE_NAME }}:latest`
            
            To deploy on Koyeb:
            ```bash
            koyeb services update <service-id> \
              --docker ${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.tag }} \
              --env PYTHONPATH=src --env UVICORN_PORT=8080 \
              --port 8080:http --route /:8080 --checks 8080:http:/healthz
            ```

  deploy-staging:
    if: ${{ secrets.KOYEB_TOKEN != '' && secrets.KOYEB_SERVICE_ID_STAGING != '' }}
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
      KOYEB_SERVICE: ${{ secrets.KOYEB_SERVICE_ID_STAGING }}
      IMAGE_NAME: greenbluegreen/bg-stremio-addon
    steps:
      - name: Compute tag
        id: tags
        run: |
          echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
      - name: Install Koyeb CLI
        run: curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/main/install.sh | sh
      - name: Deploy to staging
        run: |
          koyeb services update "$KOYEB_SERVICE" \
            --docker "$IMAGE_NAME:${{ steps.tags.outputs.tag }}" \
            --env PYTHONPATH=src --env UVICORN_PORT=8080 \
            --port 8080:http --route /:8080 --checks 8080:http:/healthz

